name: Deploy Static Site via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/static-site
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/static-site
          docker push $IMAGE_NAME:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/static-site
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            docker pull $IMAGE_NAME:latest &&
            docker stop static-container || true &&
            docker rm static-container || true &&
            docker run -d -t -p 8080:80 $IMAGE_NAME:latest
          "
